services:
    laravel:
        extends:
            file: docker-compose-common.yml
            service: laravel
        ports:
            - "80:80"
            # - "8000:8000"
        depends_on:
            - mysql
            - redis

    mysql:
        extends:
            file: docker-compose-common.yml
            service: mysql
        ports:
            - "3306:3306"

    redis:
        extends:
            file: docker-compose-common.yml
            service: redis
        ports:
            - "6379:6379"

    phpmyadmin:
        extends:
            file: docker-compose-common.yml
            service: phpmyadmin
        ports:
            - "8080:80"

volumes:
    larado-mysql:
        driver: local
    larado-redis:
        driver: local
